### ISSUE TITLE
Install issues (with cmake or python setup.py install) 

### ISSUE THREAD

**Issue by makdoudN** [NVIDIA/nvvl#13]
Hi, 

Thank for providing this library :).

I have some issues with the installation process.

Just some informations about my system if needed:

- **OS Platform and Distribution** : Ubuntu 16.04
- **NVIDIA driver** : 384.111 
- **Python version**: 3.5 (conda)
- **Exact command to reproduce**:

mkdir
 build && cd build
cmake ..
make -j
sudo make install

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is NVIDIA 9.0.176
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda-9.0/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-9.0/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libavformat'
--   Found libavformat, version 57.83.100
-- Checking for module 'libavcodec'
--   Found libavcodec, version 57.107.100
-- Checking for module 'libavfilter'
--   Found libavfilter, version 6.107.100
-- Checking for module 'libavutil'
--   Found libavutil, version 55.78.100
-- Performing Test HAVE_AVSTREAM_CODECPAR
-- Performing Test HAVE_AVSTREAM_CODECPAR - Success
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of AVBSFContext
-- Check size of AVBSFContext - done
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") found components:  doxygen missing components:  dot
Doxygen build started
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nizam/nvvl/build
Scanning dependencies of target nvvl
[  9%] Building CXX object CMakeFiles/nvvl.dir/src/VideoLoader.cpp.o
[ 18%] Building CXX object CMakeFiles/nvvl.dir/src/PictureSequence.cpp.o
[ 27%] Building CXX object CMakeFiles/nvvl.dir/src/detail/CUVideoDecoder.cpp.o
[ 36%] Building CXX object CMakeFiles/nvvl.dir/src/detail/JoiningThread.cpp.o
[ 45%] Building CXX object CMakeFiles/nvvl.dir/src/detail/CUContext.cpp.o
[ 54%] Building CXX object CMakeFiles/nvvl.dir/src/detail/Decoder.cpp.o
[ 63%] Building CUDA object CMakeFiles/nvvl.dir/src/detail/cuda/imgproc.cu.o
[ 72%] Building CXX object CMakeFiles/nvvl.dir/src/detail/CUVideoParser.cpp.o
[ 81%] Building CXX object CMakeFiles/nvvl.dir/src/detail/NvDecoder.cpp.o
[ 90%] Linking CUDA device code CMakeFiles/nvvl.dir/cmake_device_link.o
[100%] Linking CXX shared library libnvvl.so
/usr/bin/ld: cannot find -lnvcuvid
collect2: error: ld returned 1 exit status
CMakeFiles/nvvl.dir/build.make:246: recipe for target 'libnvvl.so' failed
make[2]: *** [libnvvl.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nvvl.dir/all' failed
make[1]: *** [CMakeFiles/nvvl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
[sudo] password for nizam: 
[  9%] Linking CXX shared library libnvvl.so
/usr/bin/ld: cannot find -lnvcuvid
collect2: error: ld returned 1 exit status
CMakeFiles/nvvl.dir/build.make:246: recipe for target 'libnvvl.so' failed
make[2]: *** [libnvvl.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nvvl.dir/all' failed
make[1]: *** [CMakeFiles/nvvl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

(same error with python setup.py install)

The issue seems to be here ***/usr/bin/ld: cannot find -lnvcuvid*** but with my current knowledge I am blocked here ;)

Do you have some idea to solve this issue ?

Thank

**Comment by jaredcasper** [comment]
How did you install the nvidia driver?  libnvcuvid.so should be installed along with the driver.  It looks like if you've installed it using the Ubuntu package it should be in `/usr/lib/nvidia-384`.  Can you look in there to see if there is a `libnvcuvid.so` file or tell me how you installed the nvidia driver if not from the package?

**Comment by makdoudN** [comment]
Yes I have install nvidia driver using Ubuntu package. 
I have libnvcuvid.so in /usr/lib/nvidia-384.

I tried  ``export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-384/ `` which does not work.

**Comment by jaredcasper** [comment]
Hrm, that's very odd... especially with LD_LIBRARY_PATH set it should be able to find it.  Can you run `/usr/bin/ld -lnvcuvid --verbose` and see if that gives you any clues?  Maybe post the bottom of the output (the "attempt to open..." part after the "======" line). Also you can run `ldd /usr/lib/nvidia-384/libnvcuvid.so` and see if it links against any libraries that are missing. Please post the output of that as well.

**Comment by makdoudN** [comment]
I succeed to install the library using `sudo ln -s /usr/lib/nvidia-384/libnvcuvid.so /usr/lib/libnvcuvid.so`.

I am a bit confuse but here the output of  `/usr/bin/ld -lnvcuvid --verbose`  ***after***  the soft link. 


==================================================
attempt to open //usr/local/lib/x86_64-linux-gnu/libnvcuvid.so failed
attempt to open //usr/local/lib/x86_64-linux-gnu/libnvcuvid.a failed
attempt to open //lib/x86_64-linux-gnu/libnvcuvid.so failed
attempt to open //lib/x86_64-linux-gnu/libnvcuvid.a failed
attempt to open //usr/lib/x86_64-linux-gnu/libnvcuvid.so failed
attempt to open //usr/lib/x86_64-linux-gnu/libnvcuvid.a failed
attempt to open //usr/local/lib64/libnvcuvid.so failed
attempt to open //usr/local/lib64/libnvcuvid.a failed
attempt to open //lib64/libnvcuvid.so failed
attempt to open //lib64/libnvcuvid.a failed
attempt to open //usr/lib64/libnvcuvid.so failed
attempt to open //usr/lib64/libnvcuvid.a failed
attempt to open //usr/local/lib/libnvcuvid.so failed
attempt to open //usr/local/lib/libnvcuvid.a failed
attempt to open //lib/libnvcuvid.so failed
attempt to open //lib/libnvcuvid.a failed
attempt to open //usr/lib/libnvcuvid.so succeeded
-lnvcuvid (//usr/lib/libnvcuvid.so)
libm.so.6 needed by //usr/lib/libnvcuvid.so
found libm.so.6 at //lib/x86_64-linux-gnu/libm.so.6
libc.so.6 needed by //usr/lib/libnvcuvid.so
found libc.so.6 at //lib/x86_64-linux-gnu/libc.so.6
libdl.so.2 needed by //usr/lib/libnvcuvid.so
found libdl.so.2 at //lib/x86_64-linux-gnu/libdl.so.2
ld-linux-x86-64.so.2 needed by //lib/x86_64-linux-gnu/libm.so.6
found ld-linux-x86-64.so.2 at //lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
/usr/bin/ld: warning: cannot find entry symbol _start; not setting start address

ldd /usr/lib/nvidia-384/libnvcuvid.so                                                                                                     
	linux-vdso.so.1 =>  (0x00007fffea98f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f70bc62f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f70bc265000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f70bc061000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f70bcd86000)

Thank you for the library and your time. 
I think my issue is solved.

**Comment by jaredcasper** [comment]
Looks like it found `libnvcuvid.so` in `/usr/lib`.  Not sure why it wasn't finding it in `/usr/lib/nvidia-384`, but glad it's working now. :)

**Comment by shinkyo0513** [comment]
I also met the same problem, and solved it after the soft link.
