### ISSUE TITLE
Error when loading a whole video as a single sequence in PyTorch

### ISSUE THREAD

**Issue by Ivorra** [NVIDIA/nvvl#16]
Hi,

When I try to obtain sequences of the same length as the videos in the dataset,  by assigning its length (using  `nvvl.lib.nvvl_frame_count`) as the `sequence_length` parameter in `VideoDataset`, I am obtaining the following error when starting to loop the `VideoLoader`: 

File "test.py", line 88, in <module>
    for i, frame in enumerate(loader):
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/nvvl-1.0-py3.6-linux-x86_64.egg/nvvl/loader.py", line 114, in __iter__
    for b in iter(self.batch_sampler):
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 119, in __iter__
    for idx in self.sampler:
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 33, in __iter__
    return iter(range(len(self.data_source)))
ValueError: __len__() should return >= 0

I have checked some `VideoDataset` attributes such as `frame_counts`, `total_frames`, or `start_index` and noticed that they have negative values. For example, if I have two videos of 20 frames each in the dataset and assign 20 as the `sequence_length` I get: 

Frame counts: [-1, -1]
Total frames: -2
Start index: [-1, -2]

This is the whole code snippet: 

```
lib_loader = nvvl.lib.nvvl_create_video_loader_with_log(0, nvvl.lib.LogLevel_Error)
# "filenames" has two 20-frames videos.
count = nvvl.lib.nvvl_frame_count(lib_loader, str.encode(filenames[0])) 

print("Frames in the videos: {}".format(count))

processing = {"input": nvvl.ProcessDesc(type="float", color_space="RGB", dimension_order="fhwc")}

dataset = nvvl.VideoDataset(filenames, sequence_length=count, device_id=0, processing=processing)

print("Frame counts: {}".format(dataset.frame_counts))
print("Total frames: {}".format(dataset.total_frames))
print("Start index: {}".format(dataset.start_index))

loader = nvvl.VideoLoader(dataset, batch_size=1, shuffle=False, distributed=False)

for i, data in enumerate(loader):
    input = data['input']

```

Am I missing something that should be done before?

Thanks!

**Comment by jaredcasper** [comment]
You aren't missing anything, this is a bug... definitely a use case we haven't tried.

Looks like the bug is on line 209 in dataset.py:
```
            count -= self.sequence_length + 1
```
should probably be
```
            count -= self.sequence_length - 1
```
but I won't be able to confirm or take a closer look until tomorrow.

**Comment by Ivorra** [comment]
Hi,

It seems that what you suggested fixes the issue.

Thanks!!

PS: Is there a way to do the same but with videos of varying number of frames? Something similar to:
                                                                   
    Video_1 --> 13 frames          
    Video_2 --> 27 frames

    Batch_X --> (samples, sequences, channels, frames, height, width)
    Batch_1 --> (1, 1, channels, 13, height, width)
    Batch_2 --> (1, 1, channels, 27, height, width)

**Comment by jaredcasper** [comment]
Great! I'll hopefully get around to getting the fix into master soon.

There isn't a way to do that with the current pytorch wrapper, you'd have to use the C interface directly.

**Comment by Ivorra** [comment]
Alright thanks, I will take a look at the C interface then!
