### ISSUE TITLE
pytorch wrapper build error

### ISSUE THREAD

**Issue by HxiaoD** [NVIDIA/nvvl#17]
cuda8.0 and cudnn7.1.1 are installed correctly .  When run "python setup.py install", I got error "nvcc fatal   : Path to libdevice library not specified".  Information displayed  as below:

make: Nothing to be done for `default'.
make: Nothing to be done for `default'.
running install
running bdist_egg
running egg_info
writing nvvl.egg-info/PKG-INFO
writing dependency_links to nvvl.egg-info/dependency_links.txt
writing requirements to nvvl.egg-info/requires.txt
writing top-level names to nvvl.egg-info/top_level.txt
reading manifest file 'nvvl.egg-info/SOURCES.txt'
writing manifest file 'nvvl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying nvvl/lib/__init__.py -> build/lib.linux-x86_64-3.6/nvvl/lib
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.6/nvvl.lib._lib.c'
already up-to-date
cmake -Bbuild/temp.linux-x86_64-3.6/nvvl-build -H../
-- The CUDA compiler identification is unknown
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- broken
CMake Error at /home/huxiaodong/anaconda3/lib/python3.6/site-packages/cmake/data/share/cmake-3.11/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/huxiaodong/nvvl/pytorch/build/temp.linux-x86_64-3.6/nvvl-build/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_65d65/fast"
    /usr/bin/make -f CMakeFiles/cmTC_65d65.dir/build.make CMakeFiles/cmTC_65d65.dir/build
    make[1]: Entering directory `/home/huxiaodong/nvvl/pytorch/build/temp.linux-x86_64-3.6/nvvl-build/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_65d65.dir/main.cu.o
    /usr/bin/nvcc    -cudart shared    -x cu -c /home/huxiaodong/nvvl/pytorch/build/temp.linux-x86_64-3.6/nvvl-build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_65d65.dir/main.cu.o
    nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
    nvcc fatal   : Path to libdevice library not specified
    make[1]: *** [CMakeFiles/cmTC_65d65.dir/main.cu.o] Error 1
    make[1]: Leaving directory `/home/huxiaodong/nvvl/pytorch/build/temp.linux-x86_64-3.6/nvvl-build/CMakeFiles/CMakeTmp'
    make: *** [cmTC_65d65/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:7 (project)

-- Configuring incomplete, errors occurred!
See also "/home/huxiaodong/nvvl/pytorch/build/temp.linux-x86_64-3.6/nvvl-build/CMakeFiles/CMakeOutput.log".
See also "/home/huxiaodong/nvvl/pytorch/build/temp.linux-x86_64-3.6/nvvl-build/CMakeFiles/CMakeError.log".
error: command 'cmake' failed with exit status 1

Hope to see your reply！

**Comment by jaredcasper** [comment]
Looks like your cuda installation is broken.  How did you install cuda?  Maybe try removing it and reinstalling?

**Comment by HxiaoD** [comment]
hi, @jaredcasper，I can train my network with cuda and nothing seems wrong. I tried to reinstall cuda8.0, but still got errors. I don't know whether a specified version of cuda is needed to build nvvl ?

**Comment by jaredcasper** [comment]
nvvl has been tested with cuda 8.0, 9.0, and 9.1.  Have you built anything from source that used cuda, or just used prebuilt binaries to train with cuda?  How did you install cuda?  It is finding nvcc in `/usr/bin`, but is there also one in `/usr/local/cuda/bin` for example? Did `/usr/bin/cuda` come from a system package? From the error messages `/usr/bin/nvcc` won't compile a simple program, it hasn't even started to compile nvvl, its just testing if nvcc works and deciding it doesn't.
