### ISSUE TITLE
cannot read videos with nvvl_frame_count

### ISSUE THREAD

**Issue by zxwu** [NVIDIA/nvvl#18]
It seems count = lib.(self.loader, str.encode(f)) cannot open certain videos. The video is not corrupted, and is transcoded with "-crf 18 -g 4 -vf scale=480:320 -sws_flags bicubic -map v:0 -c:v libx264 -pix_fmt yuv420p -s 480x320". Some other videos transcoded with these parameters can be read correctly.

ffmpeg -i gives: 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'RMBWK_HL38.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.56.101
  Duration: 00:00:02.04, start: 0.000000, bitrate: 2420 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 480x320, 2414 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler

Any thoughts? Thanks

**Comment by zxwu** [comment]
It turns out the videos are fine...I shuffled the video list and that video can be loaded correctly. The problem seems to be when the length of filenames  (dataset.py#L207) is greater than 950...it cannot load videos any more.

**Comment by jaredcasper** [comment]
Still not sure why filenames greater than 950 weren't working for you, but it seems like you've worked around this issue some I'm going to close this for now.
