### ISSUE TITLE
Error with video load on device 1

### ISSUE THREAD

**Issue by pikerbright** [NVIDIA/nvvl#22]
I try to use device 1 to decoder video in extract_frames.cpp.
auto loader = NVVL::VideoLoader{1};

but I got error as
CUDA runtime error 33 at line 63 in file /nvvl/src/PictureSequenceImpl.h: invalid resource handle.

Please help to check this issue.

Thanks very much!

**Comment by jaredcasper** [comment]
I haven't been able to replicate this.  What version is your nvidia kernel driver?  (it'll be on the top line of the output of `nvidia-smi`, "Driver Version: xxx.yy")

**Comment by pikerbright** [comment]
@jaredcasper Thanks for trying.
My driver version: Driver Version: 384.66

**Comment by jaredcasper** [comment]
I finally got some time and found the bug here.  The problem is the code doesn't set the current GPU before creating a stream and event.  Should be able to push a fix soon.

**Comment by pikerbright** [comment]
Great! Thanks for your help!
