### ISSUE TITLE
Is the pytorch VideoDataset actually moving everything to the CPU?

### ISSUE THREAD

**Issue by Multihuntr** [NVIDIA/nvvl#24]
I was looking through the source code for the pytorch part and I looked at the return on this line https://github.com/NVIDIA/nvvl/blob/master/pytorch/nvvl/dataset.py#L363

It really looks like after loading the video files onto the GPU with the NVVL library, it pulls it back onto the CPU. Unless I've misunderstood something this line seems to defeat the purpose of using NVVL; it should keep everything on the GPU. 
I figured that I'd put an issue in just in case it is an error, since I imagine people will just download and use the pytorch bindings expecting everything to be done on the GPU.

I'm thinking that perhaps the VideoDataset object was used for benchmarking and the benchmark numbers were checking how long it took to load video frames onto the CPU, so they default to returning CPU-based tensors?

**Comment by jaredcasper** [comment]
Thanks for checking!  The `__getitem__` function of `VideoDataset` is used for random elemental access to the dataset and is meant to be used to spot check individual sequences or for debugging, etc. It is not used by `nvvl.VideoLoader`, so if that is used the decoded video frames will not be transferred to the CPU.  It does allow a `VideoDataset` to be used (sub-optimally) by a normal PyTorch `DataLoader` which expects a dataset to provide elements on the CPU.

You are correct that using this is not going to be very performant if used frequently, and the code will spit out a warning if it used enough times unless you explicitly disable the warning (see lines 348 - 354).

**Comment by Multihuntr** [comment]
Thanks for the response. Didn't read that message properly, it seems. (I see that there's another message that I missed to that effect at the bottom of the `//pytorch/README.md`). 

So, if that's NOT the correct way to use the VideoDataset, what is? There doesn't seem to be an example that obtains batches of frames without the VideoDataloader. I assume that people should just use the VideoDataset and batch them themselves?

**Comment by Multihuntr** [comment]
Oh. I see. You use the VideoDataloader because it doesn't use element access for the VideoDataset.
