### ISSUE TITLE
python setup.py install won't install with CUDA 9.0

### ISSUE THREAD

**Issue by ddkang** [NVIDIA/nvvl#3]
```Doxygen not found -- Not building documentation
CMake Error at /home/daniel_d_kang/.virtualenvs/fd/lib/python3.5/site-packages/cmake/data/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CUDA: Found unsuitable version "9.0", but required is exact
  version "9.1" (found /usr/local/cuda)
Call Stack (most recent call first):
  /home/daniel_d_kang/.virtualenvs/fd/lib/python3.5/site-packages/cmake/data/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  /home/daniel_d_kang/.virtualenvs/fd/lib/python3.5/site-packages/cmake/data/share/cmake-3.10/Modules/FindCUDA.cmake:1080 (find_package_handle_standard_args)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:86 (find_package)
  /usr/local/share/OpenCV/OpenCVConfig.cmake:105 (find_host_package)
  doc/examples/CMakeLists.txt:7 (find_package)
```

**Comment by jaredcasper** [comment]
This appears to be OpenCV's installed cmake files that are looking for the specific CUDA 9.1 version. The build files in NVVL do not request a specific version (they don't even use the FindCUDA module).

OpenCV is only optionally used by one of the example programs.  I'll throw in an option to disable even looking for it.

**Comment by jaredcasper** [comment]
Please reopen if that commit doesn't fix your problem.

It made it so you have to explicitly ask for the OpenCV of the examples to be compiled (which would be rare when compiling from the pytorch wrapper). If for whatever reason you do want the OpenCV part of the examples compiled, you'll have to figure out why your OpenCV install is requiring Cuda 9.1.

**Comment by ddkang** [comment]
Thank you! It fixed that bug.
