### ISSUE TITLE
Videoloader for classification is completed ?

### ISSUE THREAD

**Issue by omg777** [NVIDIA/nvvl#32]
#21  
I saw that @Multihuntr add some codes for handle labels.
then now we can apply this codes for any video data? (ex Imagenet VID,...)

If there is not completed things, please tell me to solve that problem together.
Thanks:)

**Comment by Multihuntr** [comment]
That's my hope. I've run the code for the basic use case, and it seems fine, you just need to define a function that takes the filename and frame number and returns the targets. I'm just not sure if I've updated the rest of the codebase for their benchmarking code properly. Of course, if you use my fork, then know that it's not actually endorsed by the maintainers of this repo; I'm just a random dude on the internet.

P.S if you need to know the transformations actually made for the random case (i.e. where the labels depend on correspondences in the images, e.g. spatiotemporal detection), I've actually written the code for that on the master of my fork as well, but I wasn't sure if I should include it in my pull request, so it's sitting as a pull request onto my own branch for now (https://github.com/Multihuntr/nvvl/pull/2).

**Comment by jaredcasper** [comment]
I merged the PR from @Multihuntr so initial support for labels is in the main branch now.
