### ISSUE TITLE
Access to dataset used for profiling

### ISSUE THREAD

**Issue by ZaidQureshi** [NVIDIA/nvvl#35]
Can you provide the dataset (or a link to the dataset) used to generate the numbers presented here:
https://github.com/NVIDIA/nvvl/tree/master/pytorch/test

Thank you.

**Comment by jon-e-barker** [comment]
It's the same dataset as was used in the superresolution example here: https://github.com/NVIDIA/nvvl/tree/master/examples/pytorch_superres

The links to the original video file and scripts for pre-processing are provided there.

Thanks!

**Comment by ZaidQureshi** [comment]
In the benchmark.py script, what is the iter time representing? Is it just a place holder for training?

**Comment by jon-e-barker** [comment]
It's the time taken to go through an iteration.  It's there so that you can compare how long a total iteration takes compared to just data loading as you change the computation that is being carried out - in the example in the script that "computation" is just the sleep command.
