### ISSUE TITLE
Include cuda.h error

### ISSUE THREAD

**Issue by HuaizhengZhang** [NVIDIA/nvvl#41]
I have installed the library successfully and compiled the example.
```
[100%] Linking CXX executable extract_frames
[100%] Built target extract_frames
[100%] Built target examples
```
But I want to use the nvvl in my own project and then I find I can not include the cuda.h.
```
extract_frames.cpp:9:18: fatal error: cuda.h: No such file or directory
compilation terminated.
```
Can you give me some advice? I am not familiar with CUDA programming.

**Comment by jaredcasper** [comment]
You need to add the cuda include directory (usually `/usr/local/cuda/include`) in the include paths for the build.  How to do so depends on the build system you are using.

**Comment by HuaizhengZhang** [comment]
@jaredcasper Thanks for your reply. 
I have tried this like this
`g++ -c ./extract_frames.cpp -o extract_frames.o -I/usr/local/cuda/include`
but I got a lot of errors:
```
In file included from /usr/local/include/VideoLoader.h:3:0,
                 from ./extract_frames.cpp:11:
/usr/local/include/PictureSequence.h:336:7: error: expected nested-name-specifier before ‘ScaleMethod’
 using ScaleMethod = NVVL_ScaleMethod;
       ^
/usr/local/include/PictureSequence.h:337:7: error: expected nested-name-specifier before ‘ChromaUpMethod’
 using ChromaUpMethod = NVVL_ChromaUpMethod;
       ^
/usr/local/include/PictureSequence.h:338:7: error: expected nested-name-specifier before ‘ColorSpace’
 using ColorSpace = NVVL_ColorSpace;
       ^
/usr/local/include/PictureSequence.h:339:7: error: expected nested-name-specifier before ‘PicLayer’
 using PicLayer = NVVL_PicLayer;
       ^
/usr/local/include/PictureSequence.h:340:7: error: expected nested-name-specifier before ‘LayerDesc’
 using LayerDesc = NVVL_LayerDesc;
       ^
/usr/local/include/PictureSequence.h:363:9: error: ‘LayerDesc’ does not name a type
         LayerDesc desc;
         ^
...
```

**Comment by jaredcasper** [comment]
You need to link against the built nvvl library.  You'll also need to include the object file from building `cuda/utils.cu` and probably tell it where to find the cuda libraries as well.  When building the examples with the included build system you can use `make VERBOSE=1 examples` to see the command lines.

**Comment by HuaizhengZhang** [comment]
@jaredcasper Thanks for your help.
