### ISSUE TITLE
random sequences

### ISSUE THREAD

**Issue by omg777** [NVIDIA/nvvl#45]
In README, what is the meaning of 'random sequences' ?
If I use NVVL, I can`t use temporal information in sequences ??

**NVVL (NVIDIA Video Loader) is a library to load random sequences of video frames from compressed video files to facilitate machine learning training.**

**Comment by jon-e-barker** [comment]
@omg777 It might make more sense if we used the word "arbitrary" rather than "random".  The point is that NVVL can efficiently load any sequence of frames from a compressed video.

I don't know what you mean by "use temporal information" - can you clarify?

**Comment by jaredcasper** [comment]
Hopefully's Jon's description answered your question.  I'm going to close this for now, please reopen if there are more questions.
