### ISSUE TITLE
Wrong calculation of psnr_metric in the model

### ISSUE THREAD

**Issue by riccardosamperna** [NVIDIA/nvvl#50]
if not self.training:
            # Following [1], remove 12 pixels around border to prevent
            # convolution edge effects affecting PSNR
            psnr_metric = psnr(prediction[:, :, :12, -12:].float() * 255,
                               target[:, :, :12, -12:].float() * 255)

Should be substituted by:
if not self.training:
            # Following [1], remove 12 pixels around border to prevent
            # convolution edge effects affecting PSNR
            psnr_metric = psnr(prediction[:, :, :12, -12:].float() * 255,
                               target[:, :, 12:, :-12].float() * 255)

**Comment by jon-e-barker** [comment]
Will fix now - thanks!
