### ISSUE TITLE
Mix up of height and width

### ISSUE THREAD

**Issue by riccardosamperna** [NVIDIA/nvvl#51]
I found something else that should be fixed in the pytorch example dataloading/dataset.py:

#TODO(jbarker): Tidy this up and remove redundant computation
            if i == 0 and self.is_cropped:
                crop_x = random.randint(0, self.image_shape[1] - self.frame_size[1])
                crop_y = random.randint(0, self.image_shape[0] - self.frame_size[0])
            elif self.is_cropped == False:
                crop_x = math.floor((self.image_shape[1] - self.frame_size[1]) / 2)
                crop_y = math.floor((self.image_shape[0] - self.frame_size[0]) / 2)
                self.crop_size = self.frame_size

            image = image[crop_x:crop_x + self.crop_size[0],
                          crop_y:crop_y + self.crop_size[1],
                          :]

For cropping you are mixing up the crop_x and the crop_y, it should be:
 image = image[crop_y:crop_y + self.crop_size[0],
                          crop_x:crop_x + self.crop_size[1],
                          :]

**Comment by jon-e-barker** [comment]
Fixed - thanks again!
