### ISSUE TITLE
Pytorch example model.py

### ISSUE THREAD

**Issue by riccardosamperna** [NVIDIA/nvvl#56]
I don't understand how you are using the FlowNet2 to calculate the optical flow.

In this line of model.py:

`flow = self.upsample(self.FlowNetSD_network(im_pair)[0]) / 16`

it looks like that the output optical flow from FlowNetSD is downscaled compared to the input im_pair, why this is the case? 
Why are you dividing by 16?

Thanks a lot for your work

**Comment by jon-e-barker** [comment]
@riccardosamperna I actually think there are two problems here.  Firstly, I think it's a mistake that we're upsampling the flow at all - in the original paper they compute flow from upsampled images and warp those directly.  I am going to update the code to do this, which would remove the need for a scaling factor at all.

However, if you _do_ upsample the flow then you need a scaling factor to account for the fact that the units of the flow are absolute pixels and the number of pixels is different in the downsampled and upsampled images. But I think that 1/16 is not the correct scaling factor for this.  

Thanks for spotting this!

**Comment by riccardosamperna** [comment]
@jon-e-barker thanks a lot for your reply. I have noticed the same thing, the FlowNetSD output a downscale flow compared to the input images. I was not sure it was the correct behavior but it turns out to be the case.

I am investigating the correct scaling factor, I keep you updated.

**Comment by riccardosamperna** [comment]
I thought about it and the solution is quite straightforward. If we are considering the magnitude of a vector in low resolution, in order to have the same vector in high resolution we should multiple the vector magnitude by the upscaling factor. Therefore in this case I think the correct scaling factor for the unit of the flow vector is the upscaling factor 4x.

Let me know what you think about this solution.

**Comment by jon-e-barker** [comment]
@riccardosamperna You are correct that a scaling factor is not needed to account for different number of pixels - FlowNet is outputting it's values in pixels in the upscaled image. I mistakenly thought previously it was pixels in the downsampled image. 

However, if you look in the training code there is a constant factor that scales the flow vectors prior to training, 20.0 is the default. So you need to multiply the output flow vectors by 0.05 prior to upscaling.

I am just training a model with these changes to test. If it all checks out I'll push update today.

**Comment by riccardosamperna** [comment]
@jon-e-barker as you suggested, I went to take a look into the flownet2 implementation and I found the constant factor _div_flow_ you mentioned. 
Do you know exactly what this constant is accounting for?

From my tests with this modification it turns out that the flow is much more accurate now.

**Comment by jon-e-barker** [comment]
@riccardosamperna  See discussion [here](https://github.com/NVIDIA/flownet2-pytorch/issues/28)

**Comment by riccardosamperna** [comment]
Thanks @jon-e-barker

**Comment by jaredcasper** [comment]
Sounds like this has been resolved so I'm going to close it for now.  Feel free to reopen if there are more questions.
