### ISSUE TITLE
Get a sequence of evenly spaced frames from a video

### ISSUE THREAD

**Issue by Kathrine94** [NVIDIA/nvvl#68]
HI, 
I see the code and readme, I find it can only get the Consecutive frames from a video. Can I use the nvvl to 
get a sequence of evenly spaced frames from a video? If it' OK ,  how can I get a sequence of evenly spaced frames from a video?

**Comment by dumbPy** [comment]
You can write a customSampler class that inherits `torch.utils.data.Sampler` and return indices that are evenly spaced.
Pass this an instance of this `customSampler` to yout `Loader` instance

**Comment by jaredcasper** [comment]
You could use a custom sampler with a sequence length of one if you want lots of frames that are widely separated.  If you want a handful of frames separate by 1 or 2 frames you could use a large sequence length and use the index_map functionality in the ProcessDesc to get the spaced frames.

There isn't functionality to do this directly over a large amount of frames though, no.
