### ISSUE TITLE
Torchscript JIT example

### ISSUE THREAD

**Issue by bhack** [NVIDIA/nvvl#72]
Now that Torscripts could be [executed on GPU](https://github.com/pytorch/pytorch/pull/12710) can you add an example that work with [JIT/Trace](https://github.com/pytorch/tutorials/blob/master/advanced_source/cpp_export.rst)?

**Comment by jaredcasper** [comment]
I won't have time to get to this anytime in the near future, but PRs would be welcome.  It seems it would involve replicating all of the functionality that is in the PyTorch wrapper in C++ to get Tensors ready to input into the Torscript model.

**Comment by bhack** [comment]
Yes it needs to use pytorch c++ interfaces without python wrapping.
