### ISSUE TITLE
Is it still maintained? 

### ISSUE THREAD

**Issue by bhack** [NVIDIA/nvvl#73]
I see no so much activity recently in the opened tickets and not so much commits.
Other Nvidia member [suggest to follow Dali](https://github.com/tensorflow/tensorflow/issues/22518#issuecomment-424827771). @NVIDIA Can we rely on this project or its going to be superseded by something else?

**Comment by jaredcasper** [comment]
It's still semi-maintained but only by me and I have other priorities right now.  Hopefully at some point the functionality will be rolled into DALI, which is an actual supported product and not just a research project/example code.

**Comment by bhack** [comment]
Ok this was my impression
