### ISSUE TITLE
Invalid codec for NvDecoder

### ISSUE THREAD

**Issue by zhaozhengChen** [NVIDIA/nvvl#79]
Hi,
I have a problem when I try to read a mp4 file on Centos7 with cuda-8.0, but the video can be read successfully on Ubuntu18.04 with cuda-9.0.
The error info:
`Invalid codec for NvDecoder
Traceback (most recent call last):
  File "train_nvvl_challenger2.py", line 248, in <module>
    main()
  File "train_nvvl_challenger2.py", line 244, in main
    manager.train()
  File "train_nvvl_challenger2.py", line 119, in train
    for instances, labels in self._train_loader:
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 264, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/cephfs/person/emmaren/neilzzchen/TSN/src/training/nvvl_video_dataset.py", line 356, in __getitem__
    num_frames = lib.nvvl_frame_count(self.loader, str.encode(filename))
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 197, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
torch.FatalError: Unhandled codec 41282 in /cephfs/person/emmaren/neilzzchen/mini_validation224/983149951.mp4`

The the output of `ffprobe <videofile>` :
`
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'challenger/mini_validation224/983149951.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
    comment         : Meipai[samsung][7.0|24][SM-G6100][Resolution:1920*1080][7.2.5][Accelerate:1.0]
  Duration: 00:00:11.80, start: 0.000000, bitrate: 169 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 224x224, 41 kb/s, 5 fps, 5 tbr, 10240 tbn, 10 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
`

**Comment by zhaozhengChen** [comment]
Is this caused by the older driver version?
The error occurred on a server which driver version is 375.66 and cuda version is 8.0.
The output is  `Older kernel module version 375.66 so using the default stream`
But when I run the same code to load the same video on a server which driver version is 390.77 and cuda version is 9.0, the output is `Kernel module version 390.77, so using our own stream`.

**Comment by jaredcasper** [comment]
This shouldn't have anything to do with the cuda version number (the "stream" in those messages refers to CUDA streams, not media streams in the file).

I'm not sure why the code is getting that codec ID of 41282 from the ffmpeg libs, which isn't h264 or h265, when trying to get the number of frames in the file since ffprobe seems to recognize the codec ok and should be using the same libs.  It's possible that the audio stream in the file is confusing it?  Could you maybe try removing that audio stream and see if that helps?

**Comment by zhaozhengChen** [comment]
Thanks for your reply.
Removing the audio stream doesn`t work.
The code got different codec ID when I tried to read different files.

**Comment by zhaozhengChen** [comment]
I wonder why the error is torch.FatalError, isn't it occurred during decoding the video?
