### ISSUE TITLE
avformat_close_input  Error

### ISSUE THREAD

**Issue by saisaiwang33** [NVIDIA/nvvl#82]
Hi ,
I installed nvvl by pytorch wrapper,using python setup.py install , however, when I import nvvl ,there is an issue :

is there anything else I need to do ?
thanks for your help.

>>> import nvvl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/software_install/anaconda2/envs/ptsnvvl/lib/python3.5/site-packages/nvvl-1.0-py3.5-linux-x86_64.egg/nvvl/__init__.py", line 1, in <module>
    from .dataset import VideoDataset,ProcessDesc
  File "/root/software_install/anaconda2/envs/ptsnvvl/lib/python3.5/site-packages/nvvl-1.0-py3.5-linux-x86_64.egg/nvvl/dataset.py", line 9, in <module>
    from . import lib
  File "/root/software_install/anaconda2/envs/ptsnvvl/lib/python3.5/site-packages/nvvl-1.0-py3.5-linux-x86_64.egg/nvvl/lib/__init__.py", line 3, in <module>
    from ._lib import lib as _lib, ffi as _ffi
ImportError: /root/software_install/anaconda2/envs/ptsnvvl/lib/python3.5/site-packages/nvvl-1.0-py3.5-linux-x86_64.egg/nvvl/lib/libnvvl.so: undefined symbol: avformat_close_input
>>>

**Comment by Kh4L** [comment]
Hi @saisaiwang33 
How did you install FFmpeg?
Can you try it again after reinstalling it as here:
```
apt-get install -y yasm wget && \
    cd /tmp && wget -q http://ffmpeg.org/releases/ffmpeg-$FFMPEG_VERSION.tar.bz2 && \
    tar xf ffmpeg-$FFMPEG_VERSION.tar.bz2 && \
    rm ffmpeg-$FFMPEG_VERSION.tar.bz2 && \
    cd ffmpeg-$FFMPEG_VERSION && \
    ./configure \
      --prefix=/usr/local \
      --disable-static \
      --disable-all \
      --disable-autodetect \
      --disable-iconv \
      --enable-shared \
      --enable-avformat \
      --enable-avcodec \
      --enable-avfilter \
      --enable-protocol=file \
      --enable-demuxer=mov,matroska \
      --enable-bsf=h264_mp4toannexb,hevc_mp4toannexb && \
    make -j8 && make install && \
    cd /tmp && rm -rf ffmpeg-$FFMPEG_VERSION
```
(taken from [here](https://github.com/NVIDIA/nvvl/blob/633099395a2e516e0aa8591bdb00ebc083b8e404/docker/Dockerfile.build#L13))

**Comment by saisaiwang33** [comment]
@Kh4L  Thanks for your help.I had solved this problem .
