### ISSUE TITLE
PyTorch 1.0 CUDA 10 dependency issues

### ISSUE THREAD

**Issue by jbohnslav** [NVIDIA/nvvl#88]
Hello,

Thanks for all your great work! I recently installed CUDA 10 and built PyTorch 1.0 from source following [this issue.](https://github.com/NVIDIA/nvvl/issues/85). I seem to be having some dependency issues. Is it a fault of my system configuration, or does NVVL require CUDA 9.2 or less?

I built the pytorch 1.0 wrapper by cd-ing into `nvvl/pytorch1.0` and running `python setup.py install --force`.

Here's the traceback: 
```
>>> import nvvl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jim/anaconda3/envs/pt/lib/python3.7/site-packages/nvvl-1.1-py3.7-linux-x86_64.egg/nvvl/__init__.py", line 1, in <module>
    from .dataset import VideoDataset,ProcessDesc
  File "/home/jim/anaconda3/envs/pt/lib/python3.7/site-packages/nvvl-1.1-py3.7-linux-x86_64.egg/nvvl/dataset.py", line 8, in <module>
    from . import _nvvl
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory
```

**Comment by guillaumevr** [comment]
Hello,
It seems you compiled with cuda 9.2. Did you link your /usr/local/cuda repository to the new /usr/local/cuda-10.0? I think the issue is coming from your configuration

**Comment by jbohnslav** [comment]
Thanks for your help! The link was created during cuda installation. You can see that here when I run `ls -la` from `/usr/local`: 
![image](https://user-images.githubusercontent.com/17788259/49836555-1a596c80-fd71-11e8-989d-bd7f0dba6aaf.png)

**Comment by guillaumevr** [comment]
Did you previously compile nvvl library with cuda 9.2? If you did, try to remove the anaconda package created and try to compile it again.

**Comment by jbohnslav** [comment]
Hello! Thanks a lot for your help @guillaumevr. I tried removing the package with pip, and it didn't fix my issue--but it did help! What did fix it was the following: remove package with pip. Delete the entire nvvl directory, and re-clone it. Change to the pytorch1.0 subdirectory and run `python setup.py install --force`. 

I assume that even with the --force command, there was some file that wasn't re-created after first building with cuda 9.2. Deletion and re-cloning fixed that.
